backend:
  name: github
  branch: master
  repo: muhammadqamar/iPlex-office-site

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "homepage"
        name: "HomePage"
        file: "markdown/page/homepage.md"
        fields:
          - name: hero
            label: Hero
            widget: object
            fields:
              - name: templateKey
                label: Template Key
                widget: hidden
                default: hero
              - name: heading
                label: Heading
              - name: description
                label: Description
                widget: markdown
              - name: headerLink
                label: eader Link
                widget: object
                fields:
                  - name: linkName
                    label: Link Name
                  - name: linkUrl
                    label: Link Url
          - name: digitalFuture
            label: Digital Future
            widget: object
            fields:
              - name: templateKey
                label: Template Key
                widget: hidden
                default: digital-Future
              - name: headingone
                label: Heading One
              - name: descriptions
                label: Descriptions
              - name: headingtwo
                label: Heading Two
              - name: digitallink
                label: Digital Link
                widget: object
                fields:
                  - name: linkname
                    label: link name
                  - name: link
                    label: link
                    widget: string
                  - name: introCards
                    label: Intro Cards
                    widget: object
                    fields:
                      - name: cards
                        label: Cards
                        widget: list
                        fields:
                          - name: cardheading
                            label: Card Heading
                          - name: cardDescription
                            label: Card Description
                          - name: cardNumber
                            label: Card Number
                            widget: number
          - name: youropportunities
            label: Your Opportunities
            widget: object
            fields:
              - name: templateKey
                label: Template Key
                widget: hidden
                default: opportunities
              - name: heading
                label: Heading
              - name: description
                label: Description
              - name: opportunitiesLink
                label: Opportunities Link
                widget: object
                fields:
                  - name: linkName
                    label: link name
                  - name: link
                    label: link
      - label: "teamPage"
        name: "Team Page"
        file: "markdown/page/teampage.md"
        fields:
          - name: templateKey
            label: Template Key
            widget: hidden
            default: "teamdata"
          - name: teamheading
            label: Team Heading
          - name: team cards
            label: Team Card
            widget: object
            fields:
              - name: cards
                label: Cards
                widget: list
                fields:
                  - name: cardimage
                    label: Card image
                    widget: image
                  - name: cardheading
                    label: Card heading
                  - name: carddescription
                    label: Card Description
