backend:
  name: github
  branch: master
  repo: muhammadqamar/iPlex-office-site

media_folder: static/img
public_folder: /img

collections:
  - name: "alllogos"
    label: "All Logos"
    files:
      - file: "markdown/logos/heading.md"
        label: "Headings"
        name: "logoheadings"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "logo-heading",
            }
          - { label: Title, name: title, widget: string }
          - { label: headingtop, name: heading top, widget: text }
          - { label: headingbottom, name: heading bottom, widget: text }
      - file: "markdown/logos/toplogo.md"
        label: "Top Logos"
        name: "toplogos"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "top-logo",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: logos,
                    name: logos,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }
      - file: "markdown/logos/bottomlogo.md"
        label: "bottom Logos"
        name: "bottomlogos"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "bottom-logo",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: logos,
                    name: logos,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }

  - name: "scott quote"
    label: "Scott Quote"
    files:
      - file: "markdown/logos/scottcote.md"
        label: "Scott Quote"
        name: "scottquote"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "scott-cote",
            }
          - { label: Title, name: title, widget: string }
          - { label: Scott name, name: scott name, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Discription, name: discription, widget: text }
          - { label: Quote break length, name: Quotebreak, widget: number }

  - name: "early request form"
    label: "Early Request Form"
    files:
      - file: "markdown/logos/requestform.md"
        label: "Request Form"
        name: "request form"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "request-form",
            }
          - { label: Title, name: title, widget: string }
          - { label: Top heading, name: top heading, widget: text }
          - { label: Bottom heading, name: bottom heading, widget: text }

  - name: "quotes slider"
    label: "Quotes Slider"
    files:
      - file: "markdown/logos/cotesslider.md"
        label: "Cotes Slider"
        name: "cotesslider"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "cotes-slider",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: logos,
                    name: logos,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: discription, name: discription, widget: text },
                        {
                          label: author name,
                          name: authorname,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }

  - name: "early users talking"
    label: "Early Users Talking"
    files:
      - file: "markdown/logos/earlyusers.md"
        label: "Early Users"
        name: "early users"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "early-users",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: User heading, name: user heading, widget: text }
          - {
              label: User Intro,
              name: user intro,
              widget: object,
              fields:
                [
                  {
                    label: Users,
                    name: users,
                    widget: list,
                    fields:
                      [
                        {
                          label: Author Discription,
                          name: author discription,
                          widget: text,
                        },
                        {
                          label: Author Image,
                          name: author image,
                          widget: image,
                        },
                        {
                          label: Author name text,
                          name: author name text,
                          widget: string,
                          default: false,
                        },
                        {
                          label: Author Name Image,
                          name: author name image,
                          widget: image,
                          default: false,
                        },
                      ],
                  },
                ],
            }

  - name: "informed chart"
    label: "Informed Chart"
    files:
      - file: "markdown/logos/infoheading.md"
        label: "Info Heading"
        name: "info heading"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "info-heading",
            }
          - { label: Title, name: title, widget: string }
          - { label: headingtop, name: heading top, widget: text }
      - file: "markdown/logos/informed.md"
        label: "Informed"
        name: "informed"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "informed-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading One, name: heading one, widget: string }
          - { label: Heading Two, name: heading two, widget: text }
          - { label: Heading Three, name: heading three, widget: text }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: Informed,
                    name: informed,
                    widget: list,
                    fields:
                      [
                        {
                          label: Infor Image,
                          name: infor image,
                          widget: image,
                        },
                        {
                          label: Infor Image Description,
                          name: infor image description,
                          widget: text,
                        },
                      ],
                  },
                ],
            }
      - file: "markdown/logos/insynch.md"
        label: "insynch"
        name: "insynch"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "in-synch",
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading One, name: heading one, widget: string }
          - { label: Heading Two, name: heading two, widget: text }
          - { label: Heading Three, name: heading three, widget: text }
          - {
              label: Insyn,
              name: insyn,
              widget: object,
              fields:
                [
                  {
                    label: insynch,
                    name: insynch,
                    widget: list,
                    fields:
                      [
                        {
                          label: Insyn Image,
                          name: insyn image,
                          widget: image,
                        },
                        {
                          label: Insyn Image Description,
                          name: insyn image description,
                          widget: text,
                        },
                      ],
                  },
                ],
            }
      - file: "markdown/logos/onTarget.md"
        label: "OnTarget"
        name: "onTarget"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "on-Target",
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading One, name: heading one, widget: string }
          - { label: Heading Two, name: heading two, widget: text }
          - { label: Heading Three, name: heading three, widget: text }
          - {
              label: Intarg,
              name: intarg,
              widget: object,
              fields:
                [
                  {
                    label: OnTarget,
                    name: onTarget,
                    widget: list,
                    fields:
                      [
                        {
                          label: Ontarg Image,
                          name: ontarg image,
                          widget: image,
                        },
                        {
                          label: OnTarg Image Description,
                          name: onTarg image description,
                          widget: text,
                        },
                      ],
                  },
                ],
            }

  - name: "main cards"
    label: "Main Cards"
    files:
      - file: "markdown/logos/maincards.md"
        label: "cards"
        name: "Cards"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "main-cards",
            }
          - { label: Title, name: title, widget: string }
          - { label: Top heading one, name: Top heading one, widget: text }
          - { label: Top heading two, name: Top heading two, widget: text }
          - {
              label: Intro Cards,
              name: intro cards,
              widget: object,
              fields:
                [
                  {
                    label: Cards,
                    name: Cards,
                    widget: list,
                    fields:
                      [
                        { label: Card Image, name: card image, widget: image },
                        { label: Card Text, name: card text, widget: text },
                        {
                          label: Card Image Two,
                          name: card image two,
                          widget: image,
                          default: false,
                        },
                      ],
                  },
                ],
            }
  - name: "buttons"
    label: "Buttons"
    files:
      - file: "markdown/logos/buttons.md"
        label: "Buttons"
        name: "buttons"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "buttons-bage",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Button heading top,
              name: button heading top,
              widget: text,
            }
          - { label: Button one, name: buttton one, widget: string }
          - { label: Button two, name: button two, widget: string }
          - { label: Button three, name: button three, widget: string }
          - {
              label: Button heading bottom,
              name: button heading bottom,
              widget: string,
            }
  - name: "popStack brings"
    label: "PopStack Brings"
    files:
      - file: "markdown/logos/popStackbrings.md"
        label: "PopStack Brings"
        name: "popStack brings"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "popStack-brings",
            }
          - { label: Title, name: title, widget: string }
          - { label: heading top, name: button heading top, widget: text }
          - { label: heading medium, name: button heading medium, widget: text }
          - { label: heading bottom, name: button heading bottom, widget: text }

  - name: "apply popstok"
    label: "Apply Popstok"
    files:
      - file: "markdown/logos/applypopstok.md"
        label: "Apply"
        name: "apply"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "apply-popstok",
            }
          - { label: Title, name: title, widget: string }
          - { label: heading one, name: heading one, widget: text }
          - { label: Apply Btn, name: apply btn, widget: string }

  - name: "privacypolicy"
    label: "privacypolicy"
    files:
      - file: "markdown/privacypolicy/privacypolicy.md"
        label: "privacy policy"
        name: "privacypolicy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-policy",
            }
          - { label: Title, name: title, widget: string }
          - { label: page Name, name: heading, widget: text }
          - { label: description, name: description, widget: markdown }

  - name: "termsofuse"
    label: "terms of use"
    files:
      - file: "markdown/termsofuse/termsofuse.md"
        label: "terms of use"
        name: "terms of use"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "termsof-use",
            }
          - { label: Title, name: title, widget: string }
          - { label: page Name, name: heading, widget: text }
          - { label: description, name: description, widget: markdown }

  - name: "stock image"
    label: "Stock Image"
    folder: "markdown/stockimages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "stock-images",
        }
      - { label: Title, name: title, widget: string }
      - {
          label: Intro,
          name: intro,
          widget: object,
          fields:
            [
              {
                label: Stockimages,
                name: stockimages,
                widget: list,
                fields:
                  [{ label: StockImage, name: stockimage, widget: image }],
              },
            ],
        }
