backend:
  name: github
  branch: master
  repo: muhammadqamar/iPlex-office-site

media_folder: static/img
public_folder: /img

collections:
  - name: "topheader"
    label: "Top Header"
    files:
      - file: "markdown/header/header.md"
        label: "Top Header"
        name: "topheader"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "top-header",
            }
          - { label: title, name: title, widget: string }
          - { label: Heading, name: heading, widget: text }
          - { label: Description, name: description, widget: markdown }
          - {
              label: Header Link,
              name: headerlink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
  - name: "digitalfuture"
    label: "Digital Future"
    files:
      - file: "markdown/digital/digital.md"
        label: "Digital Future"
        name: "digitalfuture"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "digitalfuture",
            }
          - { label: title, name: title, widget: string }
          - { label: Heading One, name: headingone, widget: text }
          - { label: Descriptions, name: descriptions, widget: text }
          - { label: Heading Two, name: headingtwo, widget: text }
          - {
              label: Digital Link,
              name: digitallink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
          - {
              label: Intro Cards,
              name: intro cards,
              widget: object,
              fields:
                [
                  {
                    label: Cards,
                    name: Cards,
                    widget: list,
                    fields:
                      [
                        {
                          label: Card heading,
                          name: cardheading,
                          widget: string,
                        },
                        {
                          label: Card Description,
                          name: carddescription,
                          widget: text,
                        },
                        {
                          label: Card Number,
                          name: cardnumber,
                          widget: number,
                        },
                      ],
                  },
                ],
            }
  - name: "youropportunities"
    label: "Your Opportunities"
    files:
      - file: "markdown/opportunities/opportunities.md"
        label: "Opportunities"
        name: "opportunities"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "opportunities",
            }
          - { label: title, name: title, widget: string }
          - { label: Heading, name: heading, widget: text }
          - { label: Description, name: description, widget: text }
          - {
              label: Opportunities Link,
              name: opportunitieslink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }

  - name: "myteam"
    label: "My Team"
    files:
      - file: "markdown/myteam/team.md"
        label: "My Teams"
        name: "myteams"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "myteamdata",
            }
          - { label: Title, name: title, widget: string }
          - { label: Team Heading, name: teamheading, widget: text }
          - {
              label: Team Card,
              name: team cards,
              widget: object,
              fields:
                [
                  {
                    label: Cards,
                    name: Cards,
                    widget: list,
                    fields:
                      [
                        {
                          label: Card heading,
                          name: cardheading,
                          widget: string,
                        },
                        {
                          label: Card Description,
                          name: carddescription,
                          widget: text,
                        },
                        { label: Card image, name: cardimage, widget: image },
                      ],
                  },
                ],
            }

  - name: "privacypolicy"
    label: "privacypolicy"
    files:
      - file: "markdown/privacypolicy/privacypolicy.md"
        label: "privacy"
        name: "privacypolicy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-policy",
            }
          - { label: Title, name: title, widget: string }
          - { label: page Name, name: heading, widget: text }
          - { label: description, name: description, widget: markdown }

  - name: "contactUs"
    label: "Contact Us"
    files:
      - file: "markdown/contactUs/contact.md"
        label: "contactUs"
        name: "contactUs"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contactUs",
            }
          - { label: title, name: title, widget: string }
          - { label: Heading, name: heading, widget: text }
          - {
              label: hrIplex Link,
              name: hriplexlink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
          - {
              label: Address,
              name: address,
              widget: object,
              fields:
                [
                  {
                    label: Address Heading,
                    name: addressheading,
                    widget: text,
                  },

                  {
                    label: Address Paragraph,
                    name: addressparagraph,
                    widget: text,
                  },

                  {
                    label: Address Street Paragraph,
                    name: addressstreetparagraph,
                    widget: text,
                  },
                ],
            }
          
          - {
              label: Phone Link,
              name: phonelink,
              widget: object,
              fields:

              - { label: Phone Heading, name: phoneheading, widget: text }
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
          - {
              label: FaceBook Link,
              name: facebooklink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
          - {
              label: Instagram Link,
              name: instagramlink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
          - {
              label: Linkedin Link,
              name: linkedinlink,
              widget: object,
              fields:
                [
                  { label: link name, name: linkname, widget: string },

                  { label: link, name: link, widget: string },
                ],
            }
